import type { Species } from '@types/species';
import { format } from 'date-fns';

const RANK_TRANSLATIONS: Record<string, string> = {
  species: '種',
  genus: '属',
  family: '科',
  order: '目',
  class: '綱',
  phylum: '門',
  kingdom: '界',
};

export class HTMLExporter {
  export(species: Species[], title: string = '野外観察図鑑'): void {
    const html = this.generateHTML(species, title);

    // 新しいウィンドウで開く
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();

      // スタイルが適用されるまで少し待ってから印刷ダイアログを表示
      setTimeout(() => {
        printWindow.print();
      }, 500);
    }
  }

  private generateHTML(species: Species[], title: string): string {
    return `
      <!DOCTYPE html>
      <html lang="ja">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${title}</title>
        <style>
          ${this.getStyles()}
        </style>
      </head>
      <body>
        <header>
          <h1>${title}</h1>
          <p class="meta">作成日: ${format(new Date(), 'yyyy年MM月dd日')}</p>
          <p class="meta">観察種数: ${species.length}種</p>
        </header>

        <main>
          ${species.map((s, i) => this.createSpeciesHTML(s, i + 1)).join('')}
        </main>

        <footer>
          <p>このデータは iNaturalist と Wikipedia から取得されました。</p>
          <p>各画像・情報のライセンスは個別に記載されています。</p>
          <p>Generated by <a href="https://fieldnote.kamataryo.com">FieldNote</a></p>
        </footer>
      </body>
      </html>
    `;
  }

  private getStyles(): string {
    return `
      * {
        box-sizing: border-box;
      }

      body {
        font-family: 'Helvetica Neue', Arial, 'Hiragino Kaku Gothic ProN', 'Hiragino Sans', Meiryo, sans-serif;
        max-width: 900px;
        margin: 0 auto;
        padding: 20px;
        line-height: 1.6;
        color: #333;
      }

      header {
        border-bottom: 3px solid #3bb2d0;
        margin-bottom: 30px;
        padding-bottom: 20px;
      }

      h1 {
        font-size: 2em;
        margin: 0 0 10px 0;
        color: #2c3e50;
      }

      .meta {
        font-size: 0.9em;
        color: #666;
        margin: 5px 0;
      }

      .species-entry {
        page-break-inside: avoid;
        margin-bottom: 40px;
        padding-bottom: 20px;
        border-bottom: 1px solid #ddd;
      }

      .species-entry:last-child {
        border-bottom: none;
      }

      .species-entry h2 {
        color: #2c3e50;
        margin: 0 0 5px 0;
        font-size: 1.5em;
      }

      .scientific-name {
        font-style: italic;
        color: #666;
        margin: 0 0 10px 0;
      }

      .species-meta {
        display: flex;
        gap: 10px;
        margin-bottom: 15px;
      }

      .badge {
        display: inline-block;
        padding: 4px 8px;
        border-radius: 4px;
        font-size: 0.85em;
        font-weight: 500;
      }

      .badge--rank {
        background-color: #e3f2fd;
        color: #1976d2;
      }

      .badge--obs {
        background-color: #f3e5f5;
        color: #7b1fa2;
      }

      .species-image {
        max-width: 100%;
        height: auto;
        margin: 15px 0;
        border-radius: 4px;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
      }

      .attribution {
        font-size: 0.85em;
        color: #999;
        margin: 5px 0 15px 0;
      }

      .description {
        margin: 15px 0;
        line-height: 1.7;
      }

      .wikipedia-link {
        display: inline-block;
        margin-top: 10px;
        color: #3bb2d0;
        text-decoration: none;
        font-weight: 500;
      }

      .wikipedia-link:hover {
        text-decoration: underline;
      }

      footer {
        margin-top: 50px;
        padding-top: 20px;
        border-top: 2px solid #ddd;
        font-size: 0.9em;
        color: #666;
        text-align: center;
      }

      footer p {
        margin: 5px 0;
      }

      footer a {
        color: #3bb2d0;
        text-decoration: none;
      }

      @media print {
        body {
          max-width: 100%;
          padding: 0;
        }

        .species-entry {
          page-break-inside: avoid;
        }

        .wikipedia-link {
          display: none;
        }
      }
    `;
  }

  private createSpeciesHTML(species: Species, index: number): string {
    const imageUrl = species.photos[0]?.url || species.wikipediaImage?.url;
    const attribution = species.photos[0]?.attribution || species.wikipediaImage?.attribution;
    const rankJa = RANK_TRANSLATIONS[species.rank] || species.rank;

    return `
      <article class="species-entry">
        <h2>${index}. ${species.commonName || species.scientificName}</h2>
        <p class="scientific-name">${species.scientificName}</p>

        <div class="species-meta">
          <span class="badge badge--rank">${rankJa}</span>
          <span class="badge badge--obs">観察数: ${species.observationCount}</span>
        </div>

        ${
          imageUrl
            ? `
          <img src="${imageUrl}" alt="${species.commonName || species.scientificName}" class="species-image">
          <p class="attribution">出典: ${attribution}</p>
        `
            : ''
        }

        ${
          species.description
            ? `
          <div class="description">
            ${species.description}
          </div>
        `
            : ''
        }

        ${
          species.wikipediaUrl
            ? `
          <a href="${species.wikipediaUrl}" class="wikipedia-link" target="_blank" rel="noopener noreferrer">
            Wikipediaで詳細を見る →
          </a>
        `
            : ''
        }
      </article>
    `;
  }
}
